"""
FAKE-SHA Backend - Analysis Record Store

Saves successful analysis results to Supabase. Database logic is separated
from route logic here for clarity and testability.

- Never raises: all errors are caught and logged.
- Returns True if the record was saved, False otherwise.
- The /analyze endpoint always returns results regardless of storage success.
"""

import logging
from typing import Any, Optional

from supabase_client import get_supabase_client

logger = logging.getLogger(__name__)

TABLE_NAME = "analysis_records"


def save_analysis_record(
    *,
    title: str,
    url: str,
    text: str,
    mode: str,
    verdict: str,
    confidence: float,
    summary: str,
    indicators: list[str],
    extraction_source: Optional[str] = None,
) -> bool:
    """
    Attempt to save an analysis record to Supabase.

    Does not raise. Logs errors and returns False on failure.
    Returns True if the record was successfully inserted.

    Args:
        title: Article title from the request.
        url: Source URL.
        text: Analyzed text content.
        mode: Analysis mode (e.g. selection_only).
        verdict: FAKE or REAL.
        confidence: Confidence score 0–1.
        summary: Human-readable explanation.
        indicators: List of detected indicators.
        extraction_source: Optional source of text extraction (e.g. full_page).

    Returns:
        True if saved successfully, False otherwise.
    """
    client = get_supabase_client()
    if client is None:
        return False

    record: dict[str, Any] = {
        "title": title or "",
        "url": url or "",
        "text": text or "",
        "mode": mode or "selection_only",
        "verdict": verdict,
        "confidence": float(confidence),
        "summary": summary or "",
        "indicators": indicators or [],
        "extraction_source": extraction_source,
    }
    # id and created_at are auto-generated by Supabase (via default values)

    try:
        client.table(TABLE_NAME).insert(record).execute()
        logger.info("Analysis record saved to Supabase (verdict=%s, url=%s)", verdict, url[:80])
        return True
    except Exception as e:
        logger.warning(
            "Failed to save analysis record to Supabase: %s. Analysis still returned to client.",
            e,
            exc_info=False,
        )
        return False
